//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ovn2_FlowControl.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_el {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_el() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ovn2_FlowControl.Resources.Strings_el", typeof(Strings_el).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string exercise_ticket_title {
            get {
                return ResourceManager.GetString("exercise_ticket_title", resourceCulture);
            }
        }
        
        internal static string exercise_ticket_desc {
            get {
                return ResourceManager.GetString("exercise_ticket_desc", resourceCulture);
            }
        }
        
        internal static string exercise_ticket_prompt_age {
            get {
                return ResourceManager.GetString("exercise_ticket_prompt_age", resourceCulture);
            }
        }
        
        internal static string exercise_ticket_youth {
            get {
                return ResourceManager.GetString("exercise_ticket_youth", resourceCulture);
            }
        }
        
        internal static string exercise_ticket_senior {
            get {
                return ResourceManager.GetString("exercise_ticket_senior", resourceCulture);
            }
        }
        
        internal static string exercise_ticket_standard {
            get {
                return ResourceManager.GetString("exercise_ticket_standard", resourceCulture);
            }
        }
        
        internal static string exercise_ticket_err_age {
            get {
                return ResourceManager.GetString("exercise_ticket_err_age", resourceCulture);
            }
        }
        
        internal static string exercise_group_title {
            get {
                return ResourceManager.GetString("exercise_group_title", resourceCulture);
            }
        }
        
        internal static string exercise_group_desc {
            get {
                return ResourceManager.GetString("exercise_group_desc", resourceCulture);
            }
        }
        
        internal static string exercise_group_prompt_count {
            get {
                return ResourceManager.GetString("exercise_group_prompt_count", resourceCulture);
            }
        }
        
        internal static string exercise_group_prompt_age {
            get {
                return ResourceManager.GetString("exercise_group_prompt_age", resourceCulture);
            }
        }
        
        internal static string exercise_group_free {
            get {
                return ResourceManager.GetString("exercise_group_free", resourceCulture);
            }
        }
        
        internal static string exercise_group_err_count {
            get {
                return ResourceManager.GetString("exercise_group_err_count", resourceCulture);
            }
        }
        
        internal static string exercise_group_err_age {
            get {
                return ResourceManager.GetString("exercise_group_err_age", resourceCulture);
            }
        }
        
        internal static string exercise_group_result_count {
            get {
                return ResourceManager.GetString("exercise_group_result_count", resourceCulture);
            }
        }
        
        internal static string exercise_group_result_total {
            get {
                return ResourceManager.GetString("exercise_group_result_total", resourceCulture);
            }
        }
        
        internal static string exercise_repeat_title {
            get {
                return ResourceManager.GetString("exercise_repeat_title", resourceCulture);
            }
        }
        
        internal static string exercise_repeat_desc {
            get {
                return ResourceManager.GetString("exercise_repeat_desc", resourceCulture);
            }
        }
        
        internal static string exercise_repeat_prompt {
            get {
                return ResourceManager.GetString("exercise_repeat_prompt", resourceCulture);
            }
        }
        
        internal static string exercise_word_title {
            get {
                return ResourceManager.GetString("exercise_word_title", resourceCulture);
            }
        }
        
        internal static string exercise_word_desc {
            get {
                return ResourceManager.GetString("exercise_word_desc", resourceCulture);
            }
        }
        
        internal static string exercise_word_prompt {
            get {
                return ResourceManager.GetString("exercise_word_prompt", resourceCulture);
            }
        }
        
        internal static string exercise_word_err_empty {
            get {
                return ResourceManager.GetString("exercise_word_err_empty", resourceCulture);
            }
        }
        
        internal static string exercise_word_err_short {
            get {
                return ResourceManager.GetString("exercise_word_err_short", resourceCulture);
            }
        }
        
        internal static string exercise_word_result {
            get {
                return ResourceManager.GetString("exercise_word_result", resourceCulture);
            }
        }
        
        internal static string settings_title {
            get {
                return ResourceManager.GetString("settings_title", resourceCulture);
            }
        }
        
        internal static string settings_desc {
            get {
                return ResourceManager.GetString("settings_desc", resourceCulture);
            }
        }
        
        internal static string settings_prompt {
            get {
                return ResourceManager.GetString("settings_prompt", resourceCulture);
            }
        }
        
        internal static string settings_saved {
            get {
                return ResourceManager.GetString("settings_saved", resourceCulture);
            }
        }
        
        internal static string menu_title {
            get {
                return ResourceManager.GetString("menu_title", resourceCulture);
            }
        }
        
        internal static string menu_exit_message {
            get {
                return ResourceManager.GetString("menu_exit_message", resourceCulture);
            }
        }
        
        internal static string menu_invalid {
            get {
                return ResourceManager.GetString("menu_invalid", resourceCulture);
            }
        }
        
        internal static string menu_press_key {
            get {
                return ResourceManager.GetString("menu_press_key", resourceCulture);
            }
        }
    }
}
